# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: Jekyll Development Environment
description: Bootstrap development environment for Github (gh-pages) + Jekyll + Bower + SCSS + JS
url: https://kaymmm.github.io/jekyll-dev-environment
author:
  name: Keith Miyake
  email: kmiyake@gc.cuny.edu
  uri: https://kaymmm.github.io/jekyll-dev-environment
  github: https://github.com/kaymmm

# mode = dev -> use live reload
# mode = prod or null -> don't use live reload
mode: dev


# source: ./
# destination: _site
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist: 
  noscript: false

# Permalink structure and pagination options
# permalink: pretty
# paginate: 10
# paginate_path: 'page:num'
# excerpt_separator: '<!--more-->'

gems:
  - jekyll-paginate
  # - jekyll-coffeescript # uncomment this to enable coffeescript
